### ISSUE TITLE
Robot styling 

### ISSUE THREAD

**Issue by SanchitArora44** [FRC-1294/frc2024#109]
Need to choose between different techniques to paint/decorate the robot using a decision matrix with factors such as time spent prepping/total time spent, quality of finished product, cost, amount of labor required

* manual sanding + spray painting
* sandblasting * spray painting
* sandblasting only
* vinyl
* Powder coating (outsourced/sponsorship)
* nothing- plain robot

**Comment by FBurkelwsd** [comment]
Bogdan: 3d printer tutorial and videos
Brayden: pop logo on to swerve cover. and pop logo for 3d printer tutorial
Cooper: Sponsors sketched onto sponsor panel for both sides. To be 3d printed and super glued or etched in with ez router.
