### ISSUE TITLE
Programming Cart upgrade

### ISSUE THREAD

**Issue by FBurkelwsd** [FRC-1294/frc2024#144]
We are upgrading the programming cart to be able to mirror our screen of Programming laptop to at least 2 monitors on the programming cart. 

Need a mount and stand set up designed/built for each monitor.

Burke purchased hdmi splitter

We need to collect hdmi, power cables and mounts for the additional monitors.

https://docs.google.com/document/d/11_DQFXt7_s3oeTSpPYa6mZbB03-xu2bmTRmxbHQxP40/edit?usp=sharing

**Comment by tcdoan** [comment]
I think two 27-inch monitors is sufficient.
