### ISSUE TITLE
School store merchandise

### ISSUE THREAD

**Issue by FBurkelwsd** [FRC-1294/frc2024#149]
We can work with the school store and contact the people in the attached email, for additional information. another reason to order more merch and update what we sell.

Burke is biased and would like a drifit/moisture wicking material option.

[Slack Message](https://pop1294.slack.com/archives/C05CECNJQET/p1696886947001389)

**Comment by jjalla** [comment]
Update: Currently working on hoodies for members. Chose a sample last Friday. Getting a quote sometime this week.

**Comment by ArvickC** [comment]
Requested sample for mentor merch. In the process of collecting merch responses from members.
