### ISSUE TITLE
Trailer Upgrades

### ISSUE THREAD

**Issue by FBurkelwsd** [FRC-1294/frc2024#150]
Trailer ramp attachments. to make loading and unloading easier. upgrade locks. Before March competitions will depend on 8020 super pit design and build

Trailer Internal improvements: Wal mounts for tools, storage, floor reinforcement (pit storage and robots have been known to puncture through the plywood floors, ratcheting straps, E-tracks

Wrapping?

Good resource: https://www.chiefdelphi.com/t/best-practices-for-outfitting-a-6-x-10-ft-trailer/429157/2

[Slack Message](https://pop1294.slack.com/archives/C05KEQE4FQQ/p1696891694035549)

**Comment by ArvickC** [comment]
has been moved into [its own project](https://github.com/orgs/FRC-1294/projects/52/views/1) and is updated from there
