### ISSUE TITLE
Battery Analyzer setup and used on all batteries

### ISSUE THREAD

**Issue by FBurkelwsd** [FRC-1294/frc2024#152]

**Comment by FBurkelwsd** [comment]
Please add more electrical members. 

https://www.andymark.com/products/computerized-battery-analyzer is the best source with additional information at the bottom of the webpage.

The analyzer can be found on the left side of the teaching station in room D125. 

Power Cords are missing but can be remade. 
Needs a USB  type cord that may be on programming cart

**Comment by ArvickC** [comment]
Results from tests are being posted into [this](https://docs.google.com/spreadsheets/d/1fv5h65i__jhz8MUchNzLFWh4bF6oEWXIpnWh8knWrRw/edit#gid=0) document

**Comment by ArvickC** [comment]
Batteries have been tested and ordered (4).
