### ISSUE TITLE
Program Shooter (Subteam Training)

### ISSUE THREAD

**Issue by ArvickC** [FRC-1294/frc2024#161]
Software will be programming a shooter/turret as subteam training.

**Comment by TejaKoripellaUwU** [comment]
Programming's Task:
This is one of the highest priority preseason tasks for programming so this is what we have to do IN ADDITION to creating a basic shooter subsystem:

- We will use the shooter development as a conduit to test our onboard VELOCITY PID skills using falcons, something we have not done before.
- We will be programming the Flywheel for basic physics simulations as well, to determine the end position of our game piece depending on the speed of our flywheel
- We will also be using the flywheel as an opportunity to test out Motion Magic, a premade form of Motion Profiling in Falcons.
-Lastly we will be experimenting with feedforward capabilities with the kF variable

Useful links:
PID tuning with phoenix tuner: https://youtube.com/watch?v=ulIbSVq6PC4

Motion Magic, kF calculations, and API for talon FX motor controllers: https://v5.docs.ctr-electronics.com/en/stable/ch16_ClosedLoop.html#setting-motion-magic-cruise-velocity-and-acceleration

Flywheel exit velocity physics: https://www.youtube.com/watch?v=g8lGrWJ6BHc&t=324s
