### ISSUE TITLE
Pathplanner 2.0 integration

### ISSUE THREAD

**Issue by TejaKoripellaUwU** [FRC-1294/frc2024#168]
Currently we are using Pathplanner 1.0 for our autonomous paths, however a new version of Pathplanner has been released with more overall control of velocity and acceleration and better UI. However along with the changes to the UI come massive API changes. This task is going to be focused on integrating our current autonomous code into this new version.

CD thread:
https://www.chiefdelphi.com/t/pathplanner-2024-beta/442364/24

GitHub docs:
https://github.com/mjansen4857/pathplanner/wiki

**Comment by Aditya9246** [comment]
Integration is completed.
A pull request has been created for the same.

To do list (as of 12/18/2023):
- Create the paths used last year using the new user interface in the new Path Planner app.
