### ISSUE TITLE
Prototype Design Concepts

### ISSUE THREAD

**Issue by ArvickC** [FRC-1294/frc2024#197]

**Comment by ArvickC** [comment]
moved to #205

**Comment by adshah2** [comment]
Still in progress. Worked on intake and launcher designs. tested 2 inch and 4 inch compressions for launchers. still have 5 inch and multi flywheels to do. intake works well from multiple dimensions but still have to actually take numbers for those. 

We still haven't tested above/below launcher but we aren't sure if its even worth testing.

**Comment by ArvickC** [comment]
Still in progress. initial testing is complete, moving on to higher fidelity versions

**Comment by SanchitAroraAAE** [comment]
Same mechanism as launcher.

**Comment by ArvickC** [comment]
Prototypes can be found in the shop. Refer to @SanchitArora44 or @adshah2 if you have questions.
