### ISSUE TITLE
Make competition electrical board

### ISSUE THREAD

**Issue by ArvickC** [FRC-1294/frc2024#199]

**Comment by ArvickC** [comment]
Bored was planned out by electrical. They are currently working on wiring the drivebase. @adshah2 is leading this, so please refer to him if there are any questions

**Comment by adshah2** [comment]
- Planned out each spark mounting
- PDH, RIO, Mini Power Module, Network Switch all mounted
- some connections created for power from sparks to PDH
- color coded all modules
- routed most power for cancoders

**Comment by ArvickC** [comment]
Are we planning on installing a polycarb panel? @adshah2

**Comment by adshah2** [comment]
base is done, as new mechanisms and sensors are added we will wire those
