### ISSUE TITLE
Respond to concerns for summer camps

### ISSUE THREAD

**Issue by ArvickC** [FRC-1294/frc2024#20]
Priority: High

**Comment by tcdoan** [comment]
@ArvickC - can you list the concerns on the description of this task?

**Comment by ArvickC** [comment]
Concerns can be found: https://docs.google.com/spreadsheets/d/1zGJtaJL7PzuLCHzvowk8sZzU2Yt6oE-nEhdRUI07kc4/edit#gid=1525758596
