### ISSUE TITLE
CAD Elevator

### ISSUE THREAD

**Issue by ArvickC** [FRC-1294/frc2024#204]
[CAD](https://cad.onshape.com/documents/094a4149d1bb7e8fbaee23a7/w/c6b8e9893fb7293c247ef16b/e/f6db4a5a6a271e94b28c8e93)

**Comment by SanchitArora44** [comment]
Same mechanism as launcher.

**Comment by SanchitAroraAAE** [comment]
Elevator CAD V1 is finished and here's a list of Todo's based on feedback/design reviews.

Todo:
* Improve L-gussets for base and first stage (ttb ones have been known to break
* Make gusset to merge top sprocket and tube (8177 style)
* Switch to simplified MP
* Add CF spring to top of first stage to help counteract gravity
* Incorporate wire/1x1 for support+ reaction bar
* Derive drivebase tubes into elevator doc
* Have channels for rope in shooter pivot
* Reference 8177 2023 for wrist design if needed
* Add a pc plate over inverted motor area for elec/sponsors/note deflection
* Throuhbore encoder on elevator (check with programming if necessary)
* CAD in shaft collars for sprockets
* CAD in hardware like bolts and rivets
* check if falcons clips dt
*  Check why are pulley bolts on carriage so long and if they need to be that long
* Tube plug for base stage to help with sturdiness/overbuild it

**Comment by SanchitAroraAAE** [comment]
All previously listed items other than a few have been completed. The remaining items are simply design requirements for other systems/will be added later based on rest of the CAD.

Todo:
* Incorporate wire/1x1 for support+ reaction bar
* Have channels for rope in shooter pivot
* Reference 8177 2023 for wrist design if needed

For all intents and purposes (unless someone identifies an issue), the elevator CAD is finished and assembled, so please give it a final review and alert me of any issues

**Comment by SanchitAroraAAE** [comment]
After merging the elevator sub-assembly into the master-assembly i noticed a few interference issues. Screenshots of said merging issues are posted below. They're fairly easy fixes and will be addressed by the end of today

![Image](https://github.com/FRC-1294/frc2024/assets/112989796/af91637c-338a-434a-b8f5-b8b487acce20)


![Image](https://github.com/FRC-1294/frc2024/assets/112989796/387879c1-c6a2-48aa-832e-b9a35bfce5cf)
