### ISSUE TITLE
Organize Finances and Order parts

### ISSUE THREAD

**Issue by ArvickC** [FRC-1294/frc2024#21]
Priority: High

All information is in the drive.

https://drive.google.com/drive/folders/1mHOcIQNfa6Mg_LR1O-sNUzjhy32k6fb7

**Comment by tcdoan** [comment]
Hi @ArvickC 

RE: All information is in the drive.

Would you edit this task and put a link to the drive?

**Comment by ArvickC** [comment]
The summer camp has finished, and all parts arrived. The current plan is to keep the extra parts in the shop for robotics or @FBurkelwsd's Engineering camp. Closing this issue.

**Comment by FBurkelwsd** [comment]
Added the recap of ASB Robotics through Eastlake HS funding to executive board
