### ISSUE TITLE
Complete CAD for DB

### ISSUE THREAD

**Issue by ArvickC** [FRC-1294/frc2024#230]
CAD: https://cad.onshape.com/documents/0c0960b306f448c5b1808000/w/ce428a1556e71539e8a0c442/e/c2db2c05d8e732b818655dd6

**Comment by SanchitAroraAAE** [comment]
CAD is mostly finished, with only a couple remaining items.

CAD Todo:
* Add crushblocks for swerve mounting to prevent overtightening bolts/bending of tube (will be done by tn)
* Add swerve module covers to the front two modules to help prevent notes getting into wheels and guide them into the intake
* CAD final bellypan to be cut out of 1/8" or 0.09" thick steel after electrical finalizes mounting on pocketed bellypan (will be done later in the season once electrical finalizes mounting)

CAM Todo:
* All drivebase parts have their CAM completed and gcode is on the CNC's USB.
* Cutsheet for drivebase parts can be found [here](https://docs.google.com/spreadsheets/d/1Zq9yUIc4pB8la6q3wei-eDanPqmv2uSeWDiXGgvR-98/edit#gid=0)

**Comment by SanchitAroraAAE** [comment]
* Crushblocks have been added
* All tube and gusset CAM is done for the drivebase and can be found on the CNCs USB

Todo for now is just finishing up CAD for swerve module covers (will be done by tn)
