### ISSUE TITLE
CAD Launcher

### ISSUE THREAD

**Issue by ArvickC** [FRC-1294/frc2024#232]

**Comment by ArvickC** [comment]
Cad can be found [here](https://cad.onshape.com/documents/094a4149d1bb7e8fbaee23a7/w/c6b8e9893fb7293c247ef16b/e/f6db4a5a6a271e94b28c8e9). Refer to Saket or @SanchitArora44 if you have questions.

**Comment by SanchitAroraAAE** [comment]
Launcher has had some extensive work done on it over the last few days, and has a few relatively minor changes to be made but will be completely finished by the Wednesday meeting.
