### ISSUE TITLE
CAD Intake

### ISSUE THREAD

**Issue by ArvickC** [FRC-1294/frc2024#234]
[CAD](https://cad.onshape.com/documents/de2219b7238de93c51b98071/w/6e406dc3ed714c4378e8e61d/e/cdebd9a37acfc0c236d6eb31)

**Comment by SanchitAroraAAE** [comment]
CAD is nearing completion with maybe 1-2 iterations left involving mostly minor fixes such as shaft retention and addition of fasteners to the CAD
