### ISSUE TITLE
First Iteration Intake

### ISSUE THREAD

**Issue by ArvickC** [FRC-1294/frc2024#235]
Reference the CAD [here](https://cad.onshape.com/documents/de2219b7238de93c51b98071/w/6e406dc3ed714c4378e8e61d/e/b067d7e9b7156db82e87226e). building this with mdf to iterate on the final design in #257

**Comment by ArvickC** [comment]
lead times for intake plates are a couple days

**Comment by esjyoon** [comment]
All polycarb tubing was cut for the first iteration of the intake. Hex shafts are nearly finished but need to be tapped w/ the 1/4 20 tapping bit. Custom parts that needed to be printed should be ready by 2/2.

**Comment by ArvickC** [comment]
Hiccups with the printed parts, re-printed and continued progress 2/3

**Comment by ArvickC** [comment]
Upcoming goals
- Mount the mdf intake with the wedge on the drivebase and test it using PWM
- Along with the pivot motor mount this should be the highest priority so we can hopefully mfg it tomorrow. Already have mounting plates cut out for intake just need go ahead on main plates
- Take a look at the current tubes and decide what needs to be recut and what is fine as is
  - if we get go-ahead on the geo re-cut and re-assemble what is necessary
  - re-wrap all the tubes (not just new ones) with tape so that there are no gaps on the surface of the tube (i don't want to be able to see any polycarb)
- Cut out and start making the 26" long polycarb roller. we'll laser cut out a testing rig for this so we can see which compression is the fastest to feed in (we want to test out 0.2", 0.15", 0.1", and 0.05"). Testing rig will also allow us to confirm the c-c for the belt
