### ISSUE TITLE
First Iteration Elevator

### ISSUE THREAD

**Issue by ArvickC** [FRC-1294/frc2024#240]
Two groups:
Group A: Led by @Ants1the1 
Group B: Led by @esjyoon 

A: Got tubing cut out, started assembling based on cad in #204 
B: Working on cutting out tubing, dimensions found in #204

**Comment by ArvickC** [comment]
Group A got the elevator mostly completed. Group B has most tubing CNC'd for the elevator

**Comment by esjyoon** [comment]
Group A fixed chain issue on elevator, with plans to either mount on the drivebase or give to electrical to wire. Group B cut out all tubing for the second elevator and began assembly, attaching most (if not all) bearing blocks to their respective places on the tubing.

**Comment by ArvickC** [comment]
Handed off to programmers 2/2
