### ISSUE TITLE
Drive Cam Testing

### ISSUE THREAD

**Issue by AadityaAgni** [FRC-1294/frc2024#252]

**Comment by SCG1171** [comment]
[DriveCam Testing.xlsx](https://github.com/FRC-1294/frc2024/files/14173924/DriveCam.Testing.xlsx)

This is the current DriveCam Excel sheet. I will update this as we move on.

**Comment by SCG1171** [comment]
[DriveCam Testing.xlsx](https://github.com/FRC-1294/frc2024/files/14442635/DriveCam.Testing.xlsx)

Here is the finished DriveCam testing. The best camera is the mini Logitech LifeCam
