### ISSUE TITLE
Emergency Contact integration

### ISSUE THREAD

**Issue by FBurkelwsd** [FRC-1294/frc2024#255]
Extracting information from competition forms for March and April.  and adding to our mentor emergency contact number list

**Comment by vkirub** [comment]
This has been completed. @FBurkelwsd - marking this as resolved. Please file a new task if we should explore docusign or something for next year signups.

**Comment by FBurkelwsd** [comment]
![image](https://github.com/FRC-1294/frc2024/assets/135162467/0968d659-dfd8-4858-85d2-17c09adddbaa)

**Comment by FBurkelwsd** [comment]
![image](https://github.com/FRC-1294/frc2024/assets/135162467/ce46f298-d74e-403e-9d11-b5b00d4f1f5c)

**Comment by FBurkelwsd** [comment]
Anyone else see something else. Not able to access all the embedded co tact's through voice

**Comment by FBurkelwsd** [comment]
Though when I go into search members pop up

**Comment by FBurkelwsd** [comment]
Nicely done
