### ISSUE TITLE
Construct bumpers for DB

### ISSUE THREAD

**Issue by ArvickC** [FRC-1294/frc2024#256]
Led by Colin, reference the CAD in #202

**Comment by esjyoon** [comment]
Cut out most of the wood for bumpers 2/3

**Comment by ArvickC** [comment]
Started assembly of bumpers 2/9


![Image](https://github.com/FRC-1294/frc2024/assets/69405114/ff8dd30a-f48a-4380-ae77-9ed3c87bb09c)

**Comment by ArvickC** [comment]
Still need to attach cloth/fabric and team numbers. Final CAD can be found [here](https://cad.onshape.com/documents/4806c351f448d3244610d1ae/w/675b82705539b0d7ce7b0350/e/b3175b3ef1f9b7f136f14b15)

**Comment by ArvickC** [comment]
Front bumpers are slightly high, and need to be lowered so the top is 7.5" off the ground to follow the guidelines. The second set of bumpers need to be constructed as well.

**Comment by ArvickC** [comment]
All bumpers are done - red ones need to get wrapped

**Comment by ArvickC** [comment]
Wrapped and painted by @Maahimodi
