### ISSUE TITLE
Second Iteration Intake (Feeder)

### ISSUE THREAD

**Issue by ArvickC** [FRC-1294/frc2024#257]
Reference the CAD [here](https://cad.onshape.com/documents/de2219b7238de93c51b98071/w/6e406dc3ed714c4378e8e61d/e/b067d7e9b7156db82e87226e). building this with aluminum to iterate, reference #235 for the first iteration

**Comment by esjyoon** [comment]
Extra feeder intake (intake extender?) will be mounted Wed 2/21.

**Comment by ArvickC** [comment]
Feeder intake had some problems, getting mounted by @adshah2 @bredisrising  2/29
