### ISSUE TITLE
Second Iteration Launcher (2/23)

### ISSUE THREAD

**Issue by ArvickC** [FRC-1294/frc2024#259]
Cad can be found [here](https://cad.onshape.com/documents/094a4149d1bb7e8fbaee23a7/w/c6b8e9893fb7293c247ef16b/e/f6db4a5a6a271e94b28c8e9). Refer @SanchitArora44 or @esjyoon if you have questions. The date for this completion is 2/21, however when our wheels arrive we will replace them

**Comment by ArvickC** [comment]
- Start assembling final launcher
  - Wrap the new polycarb rollers with tape (please wrap them nicely. don't want to see any gaps)
  - finish process the plates cut last meeting
  - Take launcher (only launcher not wrist) parts from the mdf version and begin assembling final version with those
  - get stuff needed for flywheels cut and begin that assembly
- Finish testing the c-c's for the motor mounts with the abs encoder so CAD can be adjusted if needed or we can manufacture the platesometry finalized in the CAD.

**Comment by esjyoon** [comment]
Polycarb roller parts will be replaced with their nylon counterparts Wed 2/21. Rollers will also need to be grip-taped. Launcher is waiting on 40A 3" compliant flywheels.

**Comment by ArvickC** [comment]
Mechanically complete. @FRC-1294/electronics will continue wiring

**Comment by ArvickC** [comment]
Problems with the belt skipping on the wrist. Ordered custom gears to fix belt skippage and they are arriving 3/1.

**Comment by ArvickC** [comment]
Custom 60T 20DP gears ordered and attached
