### ISSUE TITLE
Second Iteration Elevator (2/23)

### ISSUE THREAD

**Issue by ArvickC** [FRC-1294/frc2024#260]
Had problems with the tubing, new chop saw arrived 2/3, and plan on cutting tubing W5. reference the cad [here](https://cad.onshape.com/documents/094a4149d1bb7e8fbaee23a7/w/c6b8e9893fb7293c247ef16b/e/dee7cd0b2fdd71bdd5239053)

**Comment by esjyoon** [comment]
New tubing was cut out and made square 2/5, will need to be run through the CNC today (2/5)

**Comment by esjyoon** [comment]
Second iteration elevator finished and mounted as of 2/13, still need to switch out for hooks and final wrist/launcher system (ideally by 2/14)

**Comment by ArvickC** [comment]
- add and wire cameras
- finish final wiring in general (cams, motors, energy chain, etc)
- If the CNC is free i'll cut out the allum sprocket/tube mounts for the top and the pocketed elevator mounts for the backup elevator tmrw and then mech people can post process and mount it if we have enough people.
- Cut the hex shafts on the elevator motor down to be flush with the gears (we don't have the clearance to allow for longer than necessary shafts)

**Comment by ArvickC** [comment]
Mounting hooks onto elevator 2/29
Mounting new plates on elevator 2/29
