### ISSUE TITLE
Cut out tubing for RXN bars (2/19)

### ISSUE THREAD

**Issue by ArvickC** [FRC-1294/frc2024#278]
RXN bars for holding the robot steady while on the chain. CAD can be found [here](https://cad.onshape.com/documents/0c0960b306f448c5b1808000/w/ce428a1556e71539e8a0c442/e/c2db2c05d8e732b818655dd6)

**Comment by ArvickC** [comment]
Began cutting tubing. One more piece needs to get cut, refer to the cutlist next to the chop saw.

**Comment by esjyoon** [comment]
Tubing may need to be recut to 1/16th in thickness tubing, cut dimensions should still be the same
