### ISSUE TITLE
CAD Telescopic Arm Climb

### ISSUE THREAD

**Issue by ArvickC** [FRC-1294/frc2024#291]
In the process of designing a new climb mechanism for DCMP
The cad can be found [here](https://cad.onshape.com/documents/4dc67ac7195f5f32abf6ffb6/w/1da9f90cd5e7979de209d117/e/bc499e17a0174789e09fa2fc)

**Comment by SanchitAroraAAE** [comment]
CAD is completed

Changes regarding bolt placement have been made based on yesterdays design review
The Bearing block orientation is currently based off of the manufacturer's recommendations. However we can change it quite easily if necessary based on testing
