### ISSUE TITLE
Construct Telescopic Arm Climb

### ISSUE THREAD

**Issue by ArvickC** [FRC-1294/frc2024#292]
Description in #291

**Comment by SanchitAroraAAE** [comment]
* All tubes have been cut and are in the process of being marked and drilled.
* Spacers are being 3D printed
* All necessary bearing block parts are being gathered for assembly
* All CAM for custom parts will be done by eod and all manufacturing will be finished at tomorrows meeting
* 90* gearbox constructed (@Ants1the1 )
