### ISSUE TITLE
Order Deutch Pins

### ISSUE THREAD

**Issue by aditya0shah** [FRC-1294/frc2024#39]
Order electrical pins from [future electronics](https://www.futureelectronics.com/cart)

account info: 
email: electrical@team1294.org
password: Electrical1294

Order List:

![image](https://github.com/FRC-1294/frc2024/assets/59452496/0bf376e2-85f7-4e64-9189-0ebb4503217e)

**Comment by aditya0shah** [comment]
@Benstromseth @wygrangea 
Let's hold off on ordering these until we're certain we prefer Deutch for upcoming season. 
Ms. Dooley, could you bring PowerPoles (of various sizes) to next meeting for testing? 
@FRC-1294/electronics please experiment with powerpoles and document ease of putting together/durability

**Comment by wygrangea** [comment]
Sounds good @aditya0shah . I don't know that I will be able to bring much to the next meeting because I am not certain I'll be able to get into the shop. I will be able to bring the right size for the motors though, I think they use 16-18 gauge wire. I have those in my garage for FTC.

**Comment by BilledGarlic44** [comment]
For Deutsch atleast, motors use 12 gauge pins/sockets. Not sure if it's a 1:1 transfer in terms of size when it comes to powerpoles, but just wanted to let you know
