### ISSUE TITLE
Wire new Sparks/NEOs

### ISSUE THREAD

**Issue by aditya0shah** [FRC-1294/frc2024#40]
10+ NEOs and 15+ Sparks have been ordered and have arrived/arriving soon. 

All NEOs MUST be wired with 4 pin 12 awg female deutch connectors
All Sparks 
- red/black/white side MUST be wired with 4 pin 12 awg male deutch connectors
- red/black side MUST be wired with 2 pin 12 awg female deutch connectors

For both of these please use the standardized system to wire them (found on test board). Ask @TechTaco1 for questions about the standardization. 

Please make sure there is NO sloppy wiring. After putting on the pin/socket there should be no more than around 5 copper strands to be cut. Be sure that every crimp to the wire must rest on the top of the wire insulation. To ensure this, instead of free handing the strips, _make sure you measure the pin/socket against the wire to ensure you strip the perfect amount_

After any crimp, **DO THE PULL TEST**

After wiring a part, use the test board to ensure this works. 
This means either having a programmer (or one of you if you know how) run a motor through a spark you just wired or run a motor you just wired through a working spark;

**Comment by aditya0shah** [comment]
Only wire for Sparks and NEOs that @FRC-1294/mechanics requests for now with deutch. Let's hold off on wiring any others until we know which connectors to use.

**Comment by ArvickC** [comment]
NEOs and Sparks have been wired
