### ISSUE TITLE
Order Deutch Connectors

### ISSUE THREAD

**Issue by aditya0shah** [FRC-1294/frc2024#41]
Order the actual Deutch connectors themselves for a restock for the upcoming season.
@TechTaco1 please comment which connectors are on that order list we made last meeting.

**Comment by TechTaco1** [comment]
4 pin size 12 x100 more male/female
2 pin size 12 x50 more male/female
4 pin size 20 12 x30 more male/female
2 pin size 20 12 x75 more male/female

**Comment by TechTaco1** [comment]
where to buy Deutsch connectors 


![Image](https://github.com/FRC-1294/frc2024/assets/139519929/438927a2-abf6-40cc-b60c-d086d4f88a78)



DTP connectors (size 12 connectors)

DTP06-4S mouser electronics/Digi-key electronics (cannot buy from future as min order is 500)
DTP04-4p Future Electronics
DTP04-2p Future Electronics
DTP06-2s Future Electronics

DTM (size 20 connectors)

DTM04-4p Future electronics
DTM06-4s Future electronics 
DTM04-2p from distributer 
DTM06-2s Future electronics 


after we decide what connectors, we will use we can order from here.

**Comment by TechTaco1** [comment]
![Image](https://github.com/FRC-1294/frc2024/assets/139519929/ba408d94-a94d-4316-934c-97cc8ec21a60)



![Image](https://github.com/FRC-1294/frc2024/assets/139519929/8539abf8-f0b0-4872-93a7-2fde32332c33)



![Image](https://github.com/FRC-1294/frc2024/assets/139519929/46575fdc-b557-4f90-be0a-1d4374c58520)

**Comment by wygrangea** [comment]
Next step: meet to inventory and make a final connector decision with Ben. plan for 8/14 6:30pm
