### ISSUE TITLE
Farmers Market

### ISSUE THREAD

**Issue by aditya0shah** [FRC-1294/frc2024#47]
We will be going to the Farmer's Markets on August 16th and September 6th.
Still need to contact Deb.

**Comment by BilledGarlic4** [comment]
August 16th seems like a tough deadline to meet for arm V2 and new intake considering our current progress. Is the robot something we absolutely need to have finished by the farmers market or is it fine if it's just a drivebase moving around?

**Comment by Eshan-Feroz** [comment]
That should be fine considering main point of farmers market is for people
to get interested. A drivebase is enough.

**Comment by Eshan-Feroz** [comment]
Assigned @ArishaG

**Comment by FBurkelwsd** [comment]
Things we want to design/compile:
Materials needed for set up
Directors and member input on content 
Transport 
Student leaders 
Goals

**Comment by Eshan-Feroz** [comment]
Compiled a list of materials for set up found below, waiting for board/mentor input: 
https://docs.google.com/document/d/1psVPX8ywlVnN_pbQnAhHLAIRNGYBlhEZiORjKzLEacI/edit

Will create and send out a mentor/board sign up form and a team volunteer sign up next week
@Ants1the1 (Alex T.) agreed to transport the robot.

**Comment by ArvickC** [comment]
The farmers market has finished. Should I close this issue? Or would we like to have it open for further farmer market/outreach events.
