### ISSUE TITLE
Swerve Couch/Go Kart

### ISSUE THREAD

**Issue by ArvickC** [FRC-1294/frc2024#5]
Priority: Mid

Want to make MK2 Swerve drive base- with some sort of seating arrangement. Good training for all sub-teams, and can be used at outreach events.

**Comment by aditya0shah** [comment]
First @FRC-1294/mechanics team to make Swerve chassis with Mk2 modules. Then @FRC-1294/electronics will wire and pass it off to @FRC-1294/software for programming.

**Comment by BilledGarlic44** [comment]
New CAD'ers create and iterate chassis design/CAD with seat, and driver station before handing it off to @FRC-1294/mechanics manufacture and build
