### ISSUE TITLE
Programming Bootcamp Outreach Peachjar

### ISSUE THREAD

**Issue by Eshan-Feroz** [FRC-1294/frc2024#55]
Need to set up Peachjar for programming bootcamp to advertise to public

**Comment by jjalla** [comment]
Talked to Arisha about this on Thursday. She said she passed it on to Aakarsh and he should be posting soon. @Agrawal-Aakarsh is there an update?

**Comment by Agrawal-Aakarsh** [comment]
yeah. i sent it out on thursday itself.
