### ISSUE TITLE
Glowforge set and guide

### ISSUE THREAD

**Issue by ArvickC** [FRC-1294/frc2024#57]

**Comment by ArvickC** [comment]
Do we have updates on this? Because I know @aditya0shah and @BilledGarlic44 (I think this is sanchit, please add your name) were using it during the summer camps.

**Comment by BilledGarlic4** [comment]
In my profile i've added my name (not sure if i have to do something seperate to make it show up here). But as of now i don't believe there has been any documentation started. I'm going to be gone for the next two meetings so i'll work on it as much as i can and then add pics/final details once i get back
