### ISSUE TITLE
Student handbook revised and edited

### ISSUE THREAD

**Issue by ArvickC** [FRC-1294/frc2024#63]
https://docs.google.com/document/d/1AOk_xBVYdO1fB4qKilQEy7EBKzj0eN-ItxZlicMxWxM/edit?usp=sharing is the current handbook.

First round of comment round up and edits will be August 2nd.

**Comment by ArvickC** [comment]
@jjalla and I revised the handbook. We still need to revise a mission statement, attendance policy, and finances. It's worth having a meeting between the board and mentors to finalize an attendance system for the next season.

**Comment by FBurkelwsd** [comment]
We need to do research on our merchandise @ArishaG /

**Comment by geeknoid** [comment]
Can this issue be closed?

**Comment by jjalla** [comment]
PM board needs to approve it and then we will officially be done.
