### ISSUE TITLE
Replace Swerve Modules

### ISSUE THREAD

**Issue by Ants1the1** [FRC-1294/frc2024#73]
Convert the current drive base of Riptide to use the MK4 Swerve modules. Keep using the Sparks that are already on the drive base.

Mk4 info https://www.swervedrivespecialties.com/products/mk4-swerve-module

Mk4 assembly video
https://youtu.be/PZWl8-QA-2U

**Comment by aditya0shah** [comment]
@TechTaco1 Work with programming to label sparks with their CAN id after wiring them to mk4.

**Comment by TechTaco1** [comment]
After today, one module is fully wired and routed, complications in wiring for front right module as there is no space for sparks, back left module as ther is an old neo

**Comment by Ants1the1** [comment]
Mechanically I believe the modules are completely finished. They are mounted, assembled and have loctite on the bolts that need them.
We might change half bolts that attach them to the frame for longer Phillips head 10-32 bolts to allow us to attach our bumpers.![PXL_20230811_210619876.jpg](https://github.com/FRC-1294/frc2024/assets/137527320/b821dbd4-b062-4c36-b3f9-891d53181954)
