### ISSUE TITLE
Updated designing pit inspired by teds work

### ISSUE THREAD

**Issue by FBurkelwsd** [FRC-1294/frc2024#75]
We have drawings in Onenote and a rough cad started in onshape. We have purchased milwaukee bins and storage to integrate into the pit

**Comment by SanchitArora44** [comment]
do we plan on buying the two workbenches we thought of incorporating into the pit design? or will that depend on the final CAD?

**Comment by FBurkelwsd** [comment]
Want to say we have enough 8020 to make our own workbenches. @TJScher can you add your 8020 calculations to confirm.
the cad design process is our place to iterate our designs for layout as well.
