### ISSUE TITLE
Bumper attachment

### ISSUE THREAD

**Issue by FBurkelwsd** [FRC-1294/frc2024#76]

**Comment by FBurkelwsd** [comment]
https://www.chiefdelphi.com/t/bumper-attachment-successful-options/347154 has a thread of different attachment types.
This year we tried: rivnuts, and quick release pins.

**Comment by FBurkelwsd** [comment]
COntinuing to use our zbracket for the sides, and the 10/32 bolts holding the swerve modules in place. with a low torque drill with socket attachment to make securing the nylock quicker.

**Comment by ArvickC** [comment]
Compiled to #202
