### ISSUE TITLE
Review Swerve Drive Skew and Second Order Kinematics Whitepaper

### ISSUE THREAD

**Issue by tcdoan** [FRC-1294/frc2024#80]
https://www.chiefdelphi.com/t/whitepaper-swerve-drive-skew-and-second-order-kinematics/416964

**Comment by tcdoan** [comment]
PR: https://github.com/wpilibsuite/allwpilib/pull/5425

**Comment by TejaKoripellaUwU** [comment]
I think I found out the reason for the horrendous getRate() readings from the navX:

https://github.com/kauailabs/navxmxp/issues/69

we have to use the getRawGyroZ() method instead
