### ISSUE TITLE
Test Board

### ISSUE THREAD

**Issue by ArvickC** [FRC-1294/frc2024#9]
Priority: Mid/High

A test board where we can plug in Sparks, CAN, and Motors to see if they are working.

**Comment by aditya0shah** [comment]
Work with design team to CAD an acrylic/polycarb plate to house different elec equipment to make the test board

**Comment by BilledGarlic44** [comment]
Elec board is cut out. Needs post processing, followed by fitting and mounting of elec components by elec subteam

**Comment by aditya0shah** [comment]
Have CNC'D the board and attached all electrical components. All that's left is wiring the board.

**Comment by TechTaco1** [comment]
Radio wired to roborio, battery wired to PDP, cannot finish wiring until deutsch pins and connectors are ordered.

**Comment by aditya0shah** [comment]
Just have radio/1 talon left to do eventually
